package com.grash.model.enums;

public enum PermissionEntity {
    PEOPLE_AND_TEAMS,
    CATEGORIES,
    WORK_ORDERS,
    PREVENTIVE_MAINTENANCES,
    ASSETS,
    PARTS_AND_MULTIPARTS,
    PURCHASE_ORDERS,
    METERS,
    VENDORS_AND_CUSTOMERS,
    FILES,
    LOCATIONS,
    SETTINGS,
    REQUESTS
}
