package com.grash.model.enums;

public enum WFSecondaryCondition {
    WORK_ORDER_PRIORITY_IS,
    WORK_ORDER_ASSET_IS,
    WORK_ORDER_LOCATION_IS,
    WORK_ORDER_USER_IS,
    WORK_ORDER_TEAM_IS,
    WORK_ORDER_CATEGORY_IS,
    WORK_ORDER_CREATED_AT_BETWEEN,
    WORK_ORDER_DUE_DATE_BETWEEN,
}
