package com.grash.model.enums;

public enum WorkflowAction {
    ASSIGN_PRIORITY_WORK_ORDER,
    ASSIGN_ASSET_WORK_ORDER,
    ASSIGN_LOCATION_WORK_ORDER,
    ASSIGN_USER_WORK_ORDER,
    ASSIGN_TEAM_WORK_ORDER,
    ASSIGN_CATEGORY_WORK_ORDER,
    ADD_CHECKLIST,
    SEND_REMINDER_EMAIL,
}
